// <auto-generated />
using System;
using HallApp.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HallApp.Infrastructure.Migrations
{
    [DbContext(typeof(HallAppDbContext))]
    [Migration("20260905190138_AddBookingDbSet")]
    partial class AddBookingDbSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingEntityServiceEntity", b =>
                {
                    b.Property<int>("BookingEntityId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceEntitiesId")
                        .HasColumnType("int");

                    b.HasKey("BookingEntityId", "ServiceEntitiesId");

                    b.HasIndex("ServiceEntitiesId");

                    b.ToTable("BookingEntityServiceEntity");
                });

            modelBuilder.Entity("HallApp.Entities.DatabaseEntities.BookingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.ToTable("BookingEntities");
                });

            modelBuilder.Entity("HallApp.Entities.DatabaseEntities.HallEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("HallEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            Name = "Hall A",
                            PricePerHour = 2000m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 100,
                            Name = "Hall B",
                            PricePerHour = 3500m
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            Name = "Hall C",
                            PricePerHour = 1500m
                        });
                });

            modelBuilder.Entity("HallApp.Entities.DatabaseEntities.ServiceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ServiceEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Projector",
                            Price = 500m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wi-Fi",
                            Price = 300m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sound",
                            Price = 700m
                        });
                });

            modelBuilder.Entity("HallEntityServiceEntity", b =>
                {
                    b.Property<int>("HallEntitiesId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceEntitiesId")
                        .HasColumnType("int");

                    b.HasKey("HallEntitiesId", "ServiceEntitiesId");

                    b.HasIndex("ServiceEntitiesId");

                    b.ToTable("HallEntityServiceEntity");
                });

            modelBuilder.Entity("BookingEntityServiceEntity", b =>
                {
                    b.HasOne("HallApp.Entities.DatabaseEntities.BookingEntity", null)
                        .WithMany()
                        .HasForeignKey("BookingEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HallApp.Entities.DatabaseEntities.ServiceEntity", null)
                        .WithMany()
                        .HasForeignKey("ServiceEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HallApp.Entities.DatabaseEntities.BookingEntity", b =>
                {
                    b.HasOne("HallApp.Entities.DatabaseEntities.HallEntity", "HallEntity")
                        .WithMany()
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HallEntity");
                });

            modelBuilder.Entity("HallEntityServiceEntity", b =>
                {
                    b.HasOne("HallApp.Entities.DatabaseEntities.HallEntity", null)
                        .WithMany()
                        .HasForeignKey("HallEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HallApp.Entities.DatabaseEntities.ServiceEntity", null)
                        .WithMany()
                        .HasForeignKey("ServiceEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
